<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE analysis [
<!ELEMENT analysis (section+)>
<!ATTLIST analysis version CDATA #REQUIRED>
<!ATTLIST analysis generated CDATA #REQUIRED>
<!ELEMENT section (item*)>
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item name CDATA #IMPLIED>
]
><analysis version="https://github.com/rfc-st/humble | v.2025-04-25" generated="2025/04/25 - 18:16:44"><section name="[0. Info]"><item name="Date">2025/04/25 - 18:16:44</item><item name="URL">https://facebook.com</item><item name="File">humble_https_facebook.com_20250425_181644_en.xml</item><item name="Note">The URL returns an error (HTTP code 400, 'Bad Request')</item><item name="Ref">https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status400</item></section><section name="[1. Enabled HTTP Security Headers]"><item>Cache-Control</item><item>Content-Security-Policy</item><item>Content-Type</item><item>Cross-Origin-Opener-Policy</item><item>Cross-Origin-Opener-Policy-Report-Only</item><item>(*) Origin-Agent-Cluster</item><item>Pragma</item><item>Report-To</item><item>(*) Reporting-Endpoints</item><item>Strict-Transport-Security</item><item>X-Content-Type-Options</item><item>X-Frame-Options</item><item>X-Xss-Protection</item></section><section name="[2. Missing HTTP Security Headers]"><item>Clear-Site-Data</item><item>Cross-Origin-Embedder-Policy</item><item>Cross-Origin-Resource-Policy</item><item>(*) NEL</item><item>(*) Permissions-Policy</item><item>Referrer-Policy</item><item>X-Permitted-Cross-Domain-Policies</item></section><section name="[3. Fingerprint HTTP Response Headers]"><item>X-Fb-Debug</item></section><section name="[4. Deprecated HTTP Response Headers/Protocols and Insecure Values]"><item>Content-Security-Policy (Deprecated Directives)</item><item>Content-Security-Policy ('base-uri' Directive Missing)</item><item>(*) Content-Security-Policy ('require-trusted-types-for' Directive Missing)</item><item>Content-Security-Policy (Too Permissive Sources)</item><item>Content-Security-Policy (Insecure Schemes)</item><item>Content-Security-Policy (Unsafe Values)</item><item>Content-Security-Policy (Unsafe Nonce)</item><item>Cross-Origin-Opener-Policy-Report-Only (No Valid Directives)</item><item>Pragma (Deprecated Header)</item><item>Report-To (Deprecated Header)</item><item>Strict-Transport-Security (Recommended Values)</item><item>Strict-Transport-Security (Required Values)</item><item>Vary (Potentially Unsafe Header)</item><item>X-XSS-Protection (Deprecated Header)</item></section><section name="[5. Empty HTTP Response Headers Values]"><item>Nothing to report, all seems OK!</item></section><section name="[6. Browser Compatibility for Enabled HTTP Security Headers]"><item name="Cache-Control">https://caniuse.com/?search=Cache-Control</item><item name="Content-Security-Policy">https://caniuse.com/?search=contentsecuritypolicy2</item><item name="Content-Type">https://caniuse.com/?search=Content-Type</item><item name="Cross-Origin-Opener-Policy">https://caniuse.com/?search=Cross-Origin-Opener-Policy</item><item name="Origin-Agent-Cluster">https://caniuse.com/?search=Origin-Agent-Cluster</item><item name="Pragma">https://caniuse.com/?search=Pragma</item><item name="Report-To">https://caniuse.com/?search=Report-To</item><item name="Reporting-Endpoints">https://caniuse.com/?search=Reporting-Endpoints</item><item name="Strict-Transport-Security">https://caniuse.com/?search=Strict-Transport-Security</item><item name="Vary">https://caniuse.com/?search=Vary</item><item name="X-Content-Type-Options">https://caniuse.com/?search=X-Content-Type-Options</item><item name="X-Frame-Options">https://caniuse.com/?search=X-Frame-Options</item><item name="X-XSS-Protection">https://caniuse.com/?search=X-XSS-Protection</item></section><section name="[7. Analysis Results]"><item>Done in 0.29 seconds! (changes with respect to the last analysis in parentheses)</item><item name="Enabled headers">13 (+1)</item><item name="Missing headers">7 (0)</item><item name="Fingerprint headers">1 (0)</item><item name="Deprecated/Insecure headers">14 (+1)</item><item name="Empty headers">0 (0)</item><item name="Findings to review">22 (+1)</item><item name="Analysis Grade">D (Review 'Deprecated/Insecure headers')</item><item name="'(*)' meaning">Experimental HTTP response directive or header</item><item name="'(*)' ref">https://mdn.io/Experimental_deprecated_obsolete</item></section></analysis>